name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTU1NDM1ZTYtNGE1MC00YTgwLTg2MjAtMmUwOTZiMzM2YzExIiwidGVuYW50X2lkIjoiZTkwOGNhY2M3ZjJiZjkyMDk5MTIwYTFmNjljNTMwYTFlMjAzYzlkYjI4ZTI2MzgzMTIzZjEwMjEwYWEyZTljYyIsImludGVybmFsX3NlY3JldCI6IjBiOTk2ZDliLWY5MmYtNDQ1ZS1hNWFmLTg4MDk0ZDQzOTQ0MyJ9.M7tauhtNRuYQKEsdmI_dt3aN-eDTh289HbC4p-QbzMg"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"